---
title: "Procedure for generating Table 1"
author: "Jie Zhou"
date: "9/21/2022"
output:  
  workflowr::wflow_html:
    toc: false
---





## source the simulation-related functions


```{r,message=FALSE,warning=FALSE,results='hide'}
library("lglasso")
library("glasso")
library("BDgraph")
library("GGMselect")
source("./code/simulation_functions.r")
```

## Table 1. 


Here we only show the code for the first part of Table 1, ```m=20```. The second part of ```m=40``` can be defined similarly. 


### code for m=20,n=10, coef=0
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=10
  e=0
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>

### code for m=20,n=10, coef=0.5
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=10
  e=0.5
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>

### code for m=20,n=10, coef=1
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=10
  e=1
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>


### code for m=20,n=20, coef=0
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=20
  e=0
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>


### code for m=20,n=20, coef=0.5
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=20
  e=0
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>


### code for m=20,n=20, coef=1
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=20
  e=0
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>


### code for m=20,n=30, coef=0
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=30
  e=0
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>

### code for m=20,n=30, coef=0.5
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=30
  e=0.5
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>


### code for m=20,n=30, coef=1
<details>
<summary> Click me </summary>

```{r,eval=FALSE}
  m=20
  n=30
  e=1
  p=80
  Nsim=50
  rho=vector("list",5)
  rho[[1]]=seq(0.001,0.3,length=20)
  rho[[2]]=seq(0.001,0.3,length=20)
  rho[[3]]=seq(0.001,0.3,length=20)
  rho[[4]]=seq(0.00001,0.1,length=10)
  rho[[5]]=seq(0.00001,0.1,length=10)
  set.seed(m+n+e+p)
  simures=power_compare1(m=m,n=n,p=p,coe=c(2,e,e),l=Nsim,rho=rho,prob=0.01,heter=T,nu=0.3)
```

</details>
